jumbo_to_lider = {
    "lacteos": "Frescos y Lácteos",
    "leches": "Leche",
    "yoghurt": "Yoghurt",
    "postres": "Postres Refrigerados",
    "mantequillas-y-margarinas": "Huevos y Mantequillas",
    "huevos": "Huevos y Mantequillas",
    "leches-cultivadas-y-bebidas-lacteas": "Leche",
    "probioticos-y-defensas": "Leche",
    "despensa": "Despensa",
    "arroz-y-legumbres": "Arroz y Legumbres",
    "pastas-y-salsas": "Pastas y Salsas",
    "coctel": "Cóctel y Snack",
    "conservas": "Conservas",
    "aderezos-y-salsas": "Aceites y Aderezos",
    "reposteria": "Harinas y Polvos",
    "harina-y-complementos": "Harinas y Polvos",
    "aceites-sal-y-condimentos": "Aceites y Aderezos",
    "instantaneos-y-sopas": "Alimentos Instantáneos",
    "comidas-etnicas": "Cocina Internacional",
    "frutas-y-verduras": "Frutas y Verduras",
    "frutas": "Frutas",
    "verduras": "Verduras",
    "frutos-secos-y-semillas": "Frutos Secos",
    "carniceria": "Carnes y Pescados",
    "vacuno": "Vacuno",
    "cerdo": "Cerdo",
    "pollo": "Pollo",
    "pavo": "Pavo",
    "cordero": "Cordero",
    "botilleria": "Bebidas y Licores",
    "bebidas-gaseosas": "Bebidas",
    "aguas-minerales": "Aguas",
    "jugos": "Jugos",
    "bebidas-energeticas": "Bebidas",
    "bebidas-isotonicas": "Bebidas",
    "limpieza": "Limpieza y Aseo",
    "papeles-hogar": "Papeles",
    "limpieza-de-ropa": "Detergentes",
    "bano-y-cocina": "Baño y Cocina",
    "pisos-y-muebles": "Pisos y Muebles",
    "aerosoles-y-desinfectantes": "Desinfección",
    "accesorios-de-limpieza": "Accesorios Aseo",
    "mascotas": "Mascotas",
    "perros": "Perro",
    "gatos": "Gato",
    "otras-mascotas": "Otras Mascotas",
}
